var namespacestored =
[
    [ "impl", "namespacestored_1_1impl.html", "namespacestored_1_1impl" ],
    [ "ArqLayer", "classstored_1_1_arq_layer.html", "classstored_1_1_arq_layer" ],
    [ "AsciiEscapeLayer", "classstored_1_1_ascii_escape_layer.html", "classstored_1_1_ascii_escape_layer" ],
    [ "BufferLayer", "classstored_1_1_buffer_layer.html", "classstored_1_1_buffer_layer" ],
    [ "Config", "structstored_1_1_config.html", null ],
    [ "CrcLayer", "classstored_1_1_crc_layer.html", "classstored_1_1_crc_layer" ],
    [ "Debugger", "classstored_1_1_debugger.html", "classstored_1_1_debugger" ],
    [ "DebugStore", "classstored_1_1_debug_store.html", "classstored_1_1_debug_store" ],
    [ "DebugStoreBase", "classstored_1_1_debug_store_base.html", "classstored_1_1_debug_store_base" ],
    [ "DebugVariant", "classstored_1_1_debug_variant.html", "classstored_1_1_debug_variant" ],
    [ "DebugVariantBase", "classstored_1_1_debug_variant_base.html", "classstored_1_1_debug_variant_base" ],
    [ "DebugVariantTyped", "classstored_1_1_debug_variant_typed.html", "classstored_1_1_debug_variant_typed" ],
    [ "DefaultConfig", "structstored_1_1_default_config.html", null ],
    [ "ExampleBasic", "classstored_1_1_example_basic.html", "classstored_1_1_example_basic" ],
    [ "ExampleBasicBase", "classstored_1_1_example_basic_base.html", "classstored_1_1_example_basic_base" ],
    [ "ExampleBasicData", "structstored_1_1_example_basic_data.html", "structstored_1_1_example_basic_data" ],
    [ "ExampleBasicObjects", "classstored_1_1_example_basic_objects.html", "classstored_1_1_example_basic_objects" ],
    [ "ExampleDebugAnotherStore", "classstored_1_1_example_debug_another_store.html", "classstored_1_1_example_debug_another_store" ],
    [ "ExampleDebugAnotherStoreBase", "classstored_1_1_example_debug_another_store_base.html", "classstored_1_1_example_debug_another_store_base" ],
    [ "ExampleDebugAnotherStoreData", "structstored_1_1_example_debug_another_store_data.html", "structstored_1_1_example_debug_another_store_data" ],
    [ "ExampleDebugAnotherStoreObjects", "classstored_1_1_example_debug_another_store_objects.html", "classstored_1_1_example_debug_another_store_objects" ],
    [ "ExampleDebugSomeStore", "classstored_1_1_example_debug_some_store.html", "classstored_1_1_example_debug_some_store" ],
    [ "ExampleDebugSomeStoreBase", "classstored_1_1_example_debug_some_store_base.html", "classstored_1_1_example_debug_some_store_base" ],
    [ "ExampleDebugSomeStoreData", "structstored_1_1_example_debug_some_store_data.html", "structstored_1_1_example_debug_some_store_data" ],
    [ "ExampleDebugSomeStoreObjects", "classstored_1_1_example_debug_some_store_objects.html", "classstored_1_1_example_debug_some_store_objects" ],
    [ "ExampleFunction", "classstored_1_1_example_function.html", "classstored_1_1_example_function" ],
    [ "ExampleFunctionBase", "classstored_1_1_example_function_base.html", "classstored_1_1_example_function_base" ],
    [ "ExampleFunctionData", "structstored_1_1_example_function_data.html", "structstored_1_1_example_function_data" ],
    [ "ExampleFunctionObjects", "classstored_1_1_example_function_objects.html", "classstored_1_1_example_function_objects" ],
    [ "ExampleHello", "classstored_1_1_example_hello.html", "classstored_1_1_example_hello" ],
    [ "ExampleHelloBase", "classstored_1_1_example_hello_base.html", "classstored_1_1_example_hello_base" ],
    [ "ExampleHelloData", "structstored_1_1_example_hello_data.html", "structstored_1_1_example_hello_data" ],
    [ "ExampleHelloObjects", "classstored_1_1_example_hello_objects.html", "classstored_1_1_example_hello_objects" ],
    [ "ExampleProtocol", "classstored_1_1_example_protocol.html", "classstored_1_1_example_protocol" ],
    [ "ExampleProtocolBase", "classstored_1_1_example_protocol_base.html", "classstored_1_1_example_protocol_base" ],
    [ "ExampleProtocolData", "structstored_1_1_example_protocol_data.html", "structstored_1_1_example_protocol_data" ],
    [ "ExampleProtocolObjects", "classstored_1_1_example_protocol_objects.html", "classstored_1_1_example_protocol_objects" ],
    [ "ExampleScope", "classstored_1_1_example_scope.html", "classstored_1_1_example_scope" ],
    [ "ExampleScopeBase", "classstored_1_1_example_scope_base.html", "classstored_1_1_example_scope_base" ],
    [ "ExampleScopeData", "structstored_1_1_example_scope_data.html", "structstored_1_1_example_scope_data" ],
    [ "ExampleScopeObjects", "classstored_1_1_example_scope_objects.html", "classstored_1_1_example_scope_objects" ],
    [ "ExampleSync", "classstored_1_1_example_sync.html", "classstored_1_1_example_sync" ],
    [ "ExampleSyncBase", "classstored_1_1_example_sync_base.html", "classstored_1_1_example_sync_base" ],
    [ "ExampleSyncData", "structstored_1_1_example_sync_data.html", "structstored_1_1_example_sync_data" ],
    [ "ExampleSyncObjects", "classstored_1_1_example_sync_objects.html", "classstored_1_1_example_sync_objects" ],
    [ "ExampleTerminal", "classstored_1_1_example_terminal.html", "classstored_1_1_example_terminal" ],
    [ "ExampleTerminalBase", "classstored_1_1_example_terminal_base.html", "classstored_1_1_example_terminal_base" ],
    [ "ExampleTerminalData", "structstored_1_1_example_terminal_data.html", "structstored_1_1_example_terminal_data" ],
    [ "ExampleTerminalObjects", "classstored_1_1_example_terminal_objects.html", "classstored_1_1_example_terminal_objects" ],
    [ "FrameMerger", "classstored_1_1_frame_merger.html", "classstored_1_1_frame_merger" ],
    [ "Function", "classstored_1_1_function.html", "classstored_1_1_function" ],
    [ "ListCmdCallbackArg", "structstored_1_1_list_cmd_callback_arg.html", "structstored_1_1_list_cmd_callback_arg" ],
    [ "ProtocolLayer", "classstored_1_1_protocol_layer.html", "classstored_1_1_protocol_layer" ],
    [ "ScratchPad", "classstored_1_1_scratch_pad.html", "classstored_1_1_scratch_pad" ],
    [ "SegmentationLayer", "classstored_1_1_segmentation_layer.html", "classstored_1_1_segmentation_layer" ],
    [ "StringEncoder", "classstored_1_1_string_encoder.html", "classstored_1_1_string_encoder" ],
    [ "TerminalLayer", "classstored_1_1_terminal_layer.html", "classstored_1_1_terminal_layer" ],
    [ "toType", "structstored_1_1to_type.html", null ],
    [ "toType< bool >", "structstored_1_1to_type_3_01bool_01_4.html", null ],
    [ "toType< char * >", "structstored_1_1to_type_3_01char_01_5_01_4.html", null ],
    [ "toType< char >", "structstored_1_1to_type_3_01char_01_4.html", null ],
    [ "toType< double >", "structstored_1_1to_type_3_01double_01_4.html", null ],
    [ "toType< float >", "structstored_1_1to_type_3_01float_01_4.html", null ],
    [ "toType< int >", "structstored_1_1to_type_3_01int_01_4.html", null ],
    [ "toType< long >", "structstored_1_1to_type_3_01long_01_4.html", null ],
    [ "toType< short >", "structstored_1_1to_type_3_01short_01_4.html", null ],
    [ "toType< signed char >", "structstored_1_1to_type_3_01signed_01char_01_4.html", null ],
    [ "toType< T * >", "structstored_1_1to_type_3_01_t_01_5_01_4.html", null ],
    [ "toType< unsigned char >", "structstored_1_1to_type_3_01unsigned_01char_01_4.html", null ],
    [ "toType< unsigned int >", "structstored_1_1to_type_3_01unsigned_01int_01_4.html", null ],
    [ "toType< unsigned long >", "structstored_1_1to_type_3_01unsigned_01long_01_4.html", null ],
    [ "toType< unsigned short >", "structstored_1_1to_type_3_01unsigned_01short_01_4.html", null ],
    [ "toType< void >", "structstored_1_1to_type_3_01void_01_4.html", null ],
    [ "Type", "structstored_1_1_type.html", "structstored_1_1_type" ],
    [ "value_bytes", "structstored_1_1value__bytes.html", "structstored_1_1value__bytes" ],
    [ "value_bytes< 0 >", "structstored_1_1value__bytes_3_010_01_4.html", "structstored_1_1value__bytes_3_010_01_4" ],
    [ "value_type", "structstored_1_1value__type.html", "structstored_1_1value__type" ],
    [ "value_type< N, 0 >", "structstored_1_1value__type_3_01_n_00_010_01_4.html", "structstored_1_1value__type_3_01_n_00_010_01_4" ],
    [ "value_type< N, 1 >", "structstored_1_1value__type_3_01_n_00_011_01_4.html", "structstored_1_1value__type_3_01_n_00_011_01_4" ],
    [ "value_type< N, 2 >", "structstored_1_1value__type_3_01_n_00_012_01_4.html", "structstored_1_1value__type_3_01_n_00_012_01_4" ],
    [ "value_type< N, 3 >", "structstored_1_1value__type_3_01_n_00_013_01_4.html", "structstored_1_1value__type_3_01_n_00_013_01_4" ],
    [ "value_type< N, 4 >", "structstored_1_1value__type_3_01_n_00_014_01_4.html", "structstored_1_1value__type_3_01_n_00_014_01_4" ],
    [ "Variable", "classstored_1_1_variable.html", "classstored_1_1_variable" ],
    [ "Variable< T, Container, true >", "classstored_1_1_variable_3_01_t_00_01_container_00_01true_01_4.html", "classstored_1_1_variable_3_01_t_00_01_container_00_01true_01_4" ],
    [ "Variant", "classstored_1_1_variant.html", "classstored_1_1_variant" ],
    [ "Variant< void >", "classstored_1_1_variant_3_01void_01_4.html", "classstored_1_1_variant_3_01void_01_4" ],
    [ "ZmqLayer", "classstored_1_1_zmq_layer.html", "classstored_1_1_zmq_layer" ],
    [ "ZmqServerStore", "classstored_1_1_zmq_server_store.html", "classstored_1_1_zmq_server_store" ],
    [ "ZmqServerStoreBase", "classstored_1_1_zmq_server_store_base.html", "classstored_1_1_zmq_server_store_base" ],
    [ "ZmqServerStoreData", "structstored_1_1_zmq_server_store_data.html", "structstored_1_1_zmq_server_store_data" ],
    [ "ZmqServerStoreObjects", "classstored_1_1_zmq_server_store_objects.html", "classstored_1_1_zmq_server_store_objects" ]
];