// Comment

// Default initialized
int32 hello
double world
int32 zero

// Explicit initialized
uint64=1234     u64
float=1.2e3   f

// array
int32[3] asdf
bool[2]=true asdfb

// scope
{
    int8 i
    int8=3 j
    (bool) fb
    {
        bool[3] ss
    }[3] subscope
}[2] scope

// blob
string[3] s
(string[5]) fun

// functions
(float) z
(float)[3] y

// Strange names
(float) a b/a;
int8 a b/c = 4
bool 4 a b/ddd/eee


