int8      an int8
int16     an int16
int32     an int32
int64     an int64
uint8     a uint8
uint16    a uint16
uint32    a uint32
uint64    a uint64
float     a float
double    a double
bool      a bool
ptr32     a ptr32
ptr64     a ptr64
blob:16   a blob
string:15 a string

{
	(int32)		an int8 + an int16
	(double)	circle area (r = /a double)
	(uint32)	length of /a string
} compute

{
	(uint32) ZMQ messages
	(uint32) object writes
} stats

(double) rand
(uint64) t (us)

