# vim: et:st=2:sts=2

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts/bootstrap.sh
      - name: build Debug
        run: scripts/build.sh Debug
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts/build.sh Release
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: cppcheck
        run: make cppcheck
        working-directory: build

      # If everything is OK, publish documentation
      - name: deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxygen/html

  build-windows-gcc:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts\bootstrap.cmd
      - name: build Debug
        run: scripts\build.cmd Debug
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts\build.cmd Release
      - name: test
        run: cmake --build . -- test
        working-directory: build

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: |
          scripts\bootstrap.cmd
          git submodule update --init --recursive
      - name: build Debug
        run: |
          call scripts\env.cmd
          mkdir build-msvc
          cd build-msvc
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . -j%NUMBER_OF_PROCESSORS% --config Debug
        shell: cmd
      - name: test
        run: cmake --build . --target RUN_TESTS --config Debug
        working-directory: build-msvc
      - name: build Release
        run: |
          call ..\scripts\env.cmd
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j%NUMBER_OF_PROCESSORS% --config Release
        shell: cmd
        working-directory: build-msvc
      - name: test
        run: cmake --build . --target RUN_TESTS --config Release
        working-directory: build-msvc

  build-mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts/bootstrap.sh
      - name: build Debug
        run: scripts/build.sh Debug
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts/build.sh Release
      - name: test
        run: cmake --build . -- test
        working-directory: build

