# vim: et:st=2:sts=2

name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts/bootstrap.sh
      - name: build Debug
        run: scripts/build.sh
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts/build.sh
      - name: test
        run: cmake --build . -- test
        working-directory: build

      # If everything is OK, publish documentation
      - name: deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doxygen/html

  build-windows-gcc:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts\bootstrap.cmd
      - name: build
        run: scripts\build.cmd Debug
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build
        run: scripts\build.cmd Release
      - name: test
        run: cmake --build . -- test
        working-directory: build

  build-mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts/bootstrap.sh
      - name: build
        run: scripts/build.sh Debug
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build
        run: scripts/build.sh Release
      - name: test
        run: cmake --build . -- test
        working-directory: build

