name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: |
          scripts/bootstrap.sh
          sudo apt install clang-tidy clang
      - name: build Debug
        run: scripts/build.sh Debug -DLIBSTORED_DEV=ON
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts/build.sh Release -DLIBSTORED_DEV=ON
      - name: test
        run: cmake --build . -- test
        working-directory: build

      # If everything is OK, publish documentation
      - name: deploy
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./sphinx/_build/html

  build-ubuntu-prev:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts/bootstrap.sh
      - name: build Debug
        run: scripts/build.sh Debug -DLIBSTORED_TESTS=ON
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts/build.sh Release -DLIBSTORED_TESTS=ON
      - name: test
        run: cmake --build . -- test
        working-directory: build

  build-windows-gcc:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts\bootstrap.cmd
      - name: build Debug
        run: scripts\build.cmd Debug "-DLIBSTORED_DEV=ON"
        shell: cmd
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts\build.cmd Release "-DLIBSTORED_DEV=ON"
        shell: cmd
      - name: test
        run: cmake --build . -- test
        working-directory: build

  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: |
          scripts\bootstrap.cmd
          git submodule update --init --recursive
      - name: build Debug
        run: |
          call scripts\env.cmd
          mkdir build-msvc
          cd build-msvc
          cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Debug -DLIBSTORED_DEV=ON ..
          cmake --build . --config Debug --target install -- -m
        shell: cmd
      - name: test
        run: cmake --build . --target RUN_TESTS --config Debug
        working-directory: build-msvc
      - name: build Release
        run: |
          call ..\scripts\env.cmd
          cmake -DCMAKE_BUILD_TYPE=Release -DLIBSTORED_DEV=ON ..
          cmake --build . --config Release --target install -- -m
        shell: cmd
        working-directory: build-msvc
      - name: test
        run: cmake --build . --target RUN_TESTS --config Release
        working-directory: build-msvc

  build-mac:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: bootstrap
        run: scripts/bootstrap.sh
      - name: build Debug
        run: scripts/build.sh Debug -DLIBSTORED_DEV=ON
      - name: test
        run: cmake --build . -- test
        working-directory: build
      - name: build Release
        run: scripts/build.sh Release -DLIBSTORED_DEV=ON
      - name: test
        run: cmake --build . -- test
        working-directory: build

